version: '3'

services:
  mysql:
    image: mysql:5.7.12
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: project_ai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: projectai
      MYSQL_PASSWORD: projectai
